services:

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my_password
      POSTGRES_DB: achileasShield_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__WebApiDatabase=Host=db;Port=5432;Database=achileasShield_db;Username=postgres;Password= Nikolakis1995
    depends_on:
      - db
    ports:
      - "5000:80"

volumes:
  db_data: